CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE TABLE IF NOT EXISTS users(
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	email VARCHAR(255) UNIQUE,
	phone VARCHAR(255) UNIQUE,
	password VARCHAR(255),
	address VARCHAR(255),
	account_type VARCHAR(255),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	username VARCHAR(255) UNIQUE
);
